"""Add new column

Revision ID: 06224794abbf
Revises: 748ee5ed261a
Create Date: 2023-11-25 16:59:05.305656

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "06224794abbf"
down_revision = "748ee5ed261a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feed_items", sa.Column(
        "source_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feed_items", "source_name")
    # ### end Alembic commands ###
