"""Add missing runs columns

Revision ID: 60118ec288f9
Revises: 105521347a4e
Create Date: 2026-01-18 13:33:09.540001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60118ec288f9'
down_revision = '105521347a4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_feeditem', 'feed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feed_feeditem', 'feeditem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feed_items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feed_items', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feed_items', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feed_items', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('feed_items', 'points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('feed_items', 'views',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('feed_items', 'num_comments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feed_items', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('feed_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feed_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feeds', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feeds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feeds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('runs', sa.Column('job_type', sa.String(length=100), nullable=False))
    op.add_column('runs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'runs', 'users', ['user_id'], ['id'])
    op.add_column('sources', sa.Column('source_type', sa.String(length=50), nullable=False))
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sources', 'resource_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feed_item_states', 'hide',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'star',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'like',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'dislike',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_items', 'feed_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_feed_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_feed_items', 'user_feed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_feed_items', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_feed_items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_feed_items', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('user_feed_items', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('user_feed_items', 'points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_feed_items', 'views',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_feed_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feed_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feeds', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_feeds', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_feeds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feeds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_feeds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feeds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feeds', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_feeds', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_feed_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feed_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feed_items', 'views',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_feed_items', 'points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_feed_items', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_feed_items', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_feed_items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_feed_items', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_feed_items', 'user_feed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_feed_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_feed_items', 'feed_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_feed_item_states', 'dislike',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'like',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'star',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_feed_item_states', 'hide',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sources', 'resource_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sources', 'source_type')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('runs', 'user_id')
    op.drop_column('runs', 'job_type')
    op.alter_column('feeds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feeds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feeds', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feed_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feed_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feed_items', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('feed_items', 'num_comments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feed_items', 'views',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('feed_items', 'points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('feed_items', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('feed_items', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feed_items', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feed_items', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feed_feeditem', 'feeditem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feed_feeditem', 'feed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
