"""Add indices for query optimization

Revision ID: 9ca3f204295d
Revises: a1b2c3d4e5f6
Create Date: 2026-01-19 15:28:55.177156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca3f204295d'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feed_items_link'), 'feed_items', ['link'], unique=False)
    op.create_index('ix_feed_items_local_id_source', 'feed_items', ['local_id', 'source_name'], unique=False)
    op.create_index(op.f('ix_feed_items_published'), 'feed_items', ['published'], unique=False)
    op.create_index(op.f('ix_feeds_source_id'), 'feeds', ['source_id'], unique=False)
    op.create_index(op.f('ix_user_feed_items_feed_item_id'), 'user_feed_items', ['feed_item_id'], unique=False)
    op.create_index(op.f('ix_user_feed_items_user_feed_id'), 'user_feed_items', ['user_feed_id'], unique=False)
    op.create_index(op.f('ix_user_feed_items_user_id'), 'user_feed_items', ['user_id'], unique=False)
    op.create_index('ix_user_feeds_user_active', 'user_feeds', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_feeds_user_active', table_name='user_feeds')
    op.drop_index(op.f('ix_user_feed_items_user_id'), table_name='user_feed_items')
    op.drop_index(op.f('ix_user_feed_items_user_feed_id'), table_name='user_feed_items')
    op.drop_index(op.f('ix_user_feed_items_feed_item_id'), table_name='user_feed_items')
    op.drop_index(op.f('ix_feeds_source_id'), table_name='feeds')
    op.drop_index(op.f('ix_feed_items_published'), table_name='feed_items')
    op.drop_index('ix_feed_items_local_id_source', table_name='feed_items')
    op.drop_index(op.f('ix_feed_items_link'), table_name='feed_items')
    # ### end Alembic commands ###
