"""Add user_item_states table

Revision ID: b1e4ca13f10d
Revises: 9ca3f204295d
Create Date: 2026-01-19 15:45:34.791186

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b1e4ca13f10d"
down_revision = "9ca3f204295d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("user_item_states",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("feed_item_id", sa.Integer(), nullable=False),
    sa.Column("read", sa.Boolean(), nullable=False),
    sa.Column("liked", sa.Boolean(), nullable=False),
    sa.Column("disliked", sa.Boolean(), nullable=False),
    sa.Column("starred", sa.Boolean(), nullable=False),
    sa.Column("hidden", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feed_item_id"], ["feed_items.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_user_item_states_id"), "user_item_states", ["id"], unique=False)
    op.create_index("ix_user_item_states_user_item", "user_item_states", ["user_id", "feed_item_id"], unique=True)
    op.create_index("ix_user_item_states_user_liked", "user_item_states", ["user_id", "liked"], unique=False)
    op.create_index("ix_user_item_states_user_read", "user_item_states", ["user_id", "read"], unique=False)
    op.create_index("ix_user_item_states_user_starred", "user_item_states", ["user_id", "starred"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_item_states_user_starred", table_name="user_item_states")
    op.drop_index("ix_user_item_states_user_read", table_name="user_item_states")
    op.drop_index("ix_user_item_states_user_liked", table_name="user_item_states")
    op.drop_index("ix_user_item_states_user_item", table_name="user_item_states")
    op.drop_index(op.f("ix_user_item_states_id"), table_name="user_item_states")
    op.drop_table("user_item_states")
    # ### end Alembic commands ###
