"""initial migration

Revision ID: fae752578fd0
Revises: 
Create Date: 2023-07-28 19:34:50.549676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fae752578fd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runs_id', table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_user_feed_items_id', table_name='user_feed_items')
    op.drop_table('user_feed_items')
    op.drop_index('ix_feeds_id', table_name='feeds')
    op.drop_table('feeds')
    op.drop_table('feed_userfeed')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_source_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_user_feeds_id', table_name='user_feeds')
    op.drop_table('user_feeds')
    op.drop_table('feed_items')
    op.drop_table('feed_feeditem')
    op.drop_index('ix_user_feed_item_states_id', table_name='user_feed_item_states')
    op.drop_table('user_feed_item_states')
    op.drop_index('ix_sources_id', table_name='sources')
    op.drop_index('ix_sources_name', table_name='sources')
    op.drop_index('ix_sources_resource_url', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sources_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sources_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_sources_resource_url', 'sources', ['resource_url'], unique=False)
    op.create_index('ix_sources_name', 'sources', ['name'], unique=False)
    op.create_index('ix_sources_id', 'sources', ['id'], unique=False)
    op.create_table('user_feed_item_states',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_feed_item_states_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('hide', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('star', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('like', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('dislike', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_feed_item_states_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_feed_item_states_id', 'user_feed_item_states', ['id'], unique=False)
    op.create_table('feed_feeditem',
    sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feeditem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name='feed_feeditem_feed_id_fkey'),
    sa.ForeignKeyConstraint(['feeditem_id'], ['feed_items.id'], name='feed_feeditem_feeditem_id_fkey')
    )
    op.create_table('feed_items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('feed_items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('published', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('local_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('article_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('num_comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='feed_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_feeds',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_feeds_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_feeds_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_feeds_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_feeds_id', 'user_feeds', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('subscriptions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='subscriptions_source_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_source_id', 'subscriptions', ['source_id'], unique=False)
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('feed_userfeed',
    sa.Column('user_feed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name='feed_userfeed_feed_id_fkey'),
    sa.ForeignKeyConstraint(['user_feed_id'], ['user_feeds.id'], name='feed_userfeed_user_feed_id_fkey')
    )
    op.create_table('feeds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='feeds_source_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feeds_pkey')
    )
    op.create_index('ix_feeds_id', 'feeds', ['id'], unique=False)
    op.create_table('user_feed_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feed_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_feed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], name='user_feed_items_feed_item_id_fkey'),
    sa.ForeignKeyConstraint(['state_id'], ['user_feed_item_states.id'], name='user_feed_items_state_id_fkey'),
    sa.ForeignKeyConstraint(['user_feed_id'], ['user_feeds.id'], name='user_feed_items_user_feed_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_feed_items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_feed_items_pkey')
    )
    op.create_index('ix_user_feed_items_id', 'user_feed_items', ['id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='runs_subscription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='runs_pkey')
    )
    op.create_index('ix_runs_id', 'runs', ['id'], unique=False)
    # ### end Alembic commands ###
